<a href="https://colab.research.google.com/github/gutak12345/Gustavo-Adolfo-Martinez-Misal/blob/master/Taller_1_(Parte_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Taller de clase python
###Gustavo Adolfo Martinez Misal
 **1  parte** 
 
 *bogota d.c 2020*

In [0]:
import numpy as np

In [0]:
# 1 vector (entre 1 y 10 )
a = np.random.randint(4, size=10)
print (a)

[3 1 2 2 1 1 0 2 1 3]


In [0]:
# 2 vector (entre 1 y 10 )
b = np.random.randint(5, size=10)
print (b)

[1 3 2 2 3 0 3 2 2 2]


In [0]:
# suma de vectores
c=(a + b)
print (c)

[4 4 4 4 4 1 3 4 3 5]


In [0]:
# concatenar los vectores
np.concatenate((a , b))

array([3, 1, 2, 2, 1, 1, 0, 2, 1, 3, 1, 3, 2, 2, 3, 0, 3, 2, 2, 2])

In [0]:
# encontrar la media ( vectores concatenados)

import statistics as stats

media = [1, 2, 0, 2, 2, 1, 3, 3, 3, 1, 0, 2, 2, 3, 1, 0, 4, 2, 1, 3]
print(stats.mean(media))  

1.8


In [0]:
#numeros mayores y minimos

vector = [1, 2, 0, 2, 2, 1, 3, 3, 3, 1, 0, 2, 2, 3, 1, 0, 4, 2, 1, 3]
min = max = vector[0]
for vector in vector:
    if vector < min:
        min = vector
    elif vector > max:
        max = vector 
print("El mínimo es " + str(min)) 
print("El máximo es " + str(max))

El mínimo es 0
El máximo es 4
